server:
  port: 8080
  servlet:
    context-path: /vidsonet

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/vidsonet}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
paypal:
  client-id: Ab2FU5u97cgWPv2X7decFTugtAHIpMcD7RCOwaJQ033uD4H_bI7qTmmtcp2wxXIuDhhjNxF8r43Od2fg
  client-secret: ELBp27evxbc7eI6GWs4RLB_KAyrswZZfIpvQmM9TdBG-7kcYo75t6Ht7ynYYsSmjLNV4rtNSWQBcx2bz
  mode: sandbox # sandbox hoặc live
  success-url: ${app.frontend-url}/membership/success
  cancel-url: ${app.frontend-url}/membership/cancel
app:
  frontend-url: http://localhost:3000
  jwt:
    secret: "YYzrYVGsu1A65dvMxYP1W+d2LcC7fAFTLoa+5kT9rj5dDNL77BPUyEsMKbGNN2G7"
    expiration: 604800000 #ms
    refresh-expiration: 2592000000 #ms
  file:
    upload-dir: ./uploads
